version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.20.0.10

  goapp:
    image: golang:1.24.3-alpine3.21
    container_name: goapp
    depends_on:
      - mysql
    volumes:
      - ./:/examples
    working_dir: /examples
    command: sh -c "sleep infinity"
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      default:
        ipv4_address: 172.20.0.20

networks:
  default:
    driver: bridge
    name: default_network
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  mysql_data: